on:
  push:

jobs:
  goblint:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: goblint/action@master
        with:
          file: 01-simple_rc.c
      - uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: goblint.sarif
  
  goblint-cmake-project:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: cmake-project
    
    steps:
      - uses: actions/checkout@v2
      - run: cmake -B build
      - uses: goblint/action@master
        with:
          file: build
      - uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: goblint.sarif
