on:
  push:

jobs:
  goblint:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: goblint/action@master
        with:
          file: 01-simple_rc.c
      - uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: goblint.sarif
  
  goblint-cmake-project:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - run: cmake -B build
        working-directory: cmake-project
      - run: ls -R
      - uses: docker://ghcr.io/goblint/analyzer:nightly
        with:
          entrypoint: ls
          args: '-R'
      - uses: docker://ghcr.io/goblint/analyzer:nightly
        with:
          entrypoint: goblint
          args: cmake-project/build/compile_commands.json
      - uses: goblint/action@master
        with:
          file: cmake-project/build/compile_commands.json
      - uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: goblint.sarif
